import type { PlayerAbility, RatingDefinition } from './types.js';

export const RATING_DEFINITIONS: RatingDefinition[] = [
  { code: 'SPD', label: 'Speed', category: 'physical', description: 'Maximum speed of the player on the field.' },
  { code: 'STR', label: 'Strength', category: 'physical', description: 'Effectiveness in physical battles, blocking, and shedding blocks.' },
  { code: 'AGI', label: 'Agility', category: 'physical', description: 'How smoothly a player moves, cuts, and dodges.' },
  { code: 'ACC', label: 'Acceleration', category: 'physical', description: 'How quickly a player reaches top speed from a standstill.' },
  { code: 'COD', label: 'Change of Direction', category: 'physical', description: 'Ability to cut or change direction without losing speed.' },
  { code: 'AWR', label: 'Awareness', category: 'general', description: 'How well a player reacts and reads unscripted plays.' },
  { code: 'JMP', label: 'Jumping', category: 'physical', description: 'Reach and vertical ability for catches and defending passes.' },
  { code: 'STA', label: 'Stamina', category: 'physical', description: 'How long a player can perform at peak levels before tiring.' },
  { code: 'INJ', label: 'Injury', category: 'general', description: 'Resistance to picking up injuries.' },
  { code: 'TGH', label: 'Toughness', category: 'general', description: 'How fast a player recovers when injured.' },
  { code: 'THP', label: 'Throw Power', category: 'offense', description: 'Maximum distance and velocity of passes.' },
  { code: 'SAC', label: 'Short Accuracy', category: 'offense', description: 'Accuracy on short throws.' },
  { code: 'MAC', label: 'Medium Accuracy', category: 'offense', description: 'Accuracy on medium throws.' },
  { code: 'DAC', label: 'Deep Accuracy', category: 'offense', description: 'Accuracy on deep throws.' },
  { code: 'RUN', label: 'Throw On The Run', category: 'offense', description: 'Accuracy while throwing outside the pocket.' },
  { code: 'PAC', label: 'Play Action', category: 'offense', description: 'Effectiveness of play-action passing fakes.' },
  { code: 'RBK', label: 'Run Block', category: 'offense', description: 'Fundamental run blocking capability.' },
  { code: 'PBK', label: 'Pass Block', category: 'offense', description: 'Fundamental pass blocking capability.' },
  { code: 'RBK_STR', label: 'Run Block Strength', category: 'offense', description: 'Raw power when run blocking.' },
  { code: 'PBK_FIN', label: 'Pass Block Finesse', category: 'offense', description: 'Technical footwork and technique for pass blocking.' },
  { code: 'IBL', label: 'Impact Blocking', category: 'offense', description: 'Blocking downfield or on screens.' },
  { code: 'CTH', label: 'Catching', category: 'offense', description: 'Base ability to secure the ball.' },
  { code: 'SRR', label: 'Short Route Running', category: 'offense', description: 'Precision on short routes.' },
  { code: 'MRR', label: 'Medium Route Running', category: 'offense', description: 'Precision on medium routes.' },
  { code: 'DRR', label: 'Deep Route Running', category: 'offense', description: 'Precision on deep routes.' },
  { code: 'RLS', label: 'Release', category: 'offense', description: 'Ability to beat press coverage off the line.' },
  { code: 'CIT', label: 'Catch In Traffic', category: 'offense', description: 'Ability to hold onto the ball while being hit.' },
  { code: 'SPC', label: 'Spectacular Catch', category: 'offense', description: 'Likelihood of making jumping or one-handed grabs.' },
  { code: 'BCV', label: 'Ball Carrier Vision', category: 'offense', description: 'Ability to find running lanes automatically.' },
  { code: 'TRK', label: 'Trucking', category: 'offense', description: 'Powering straight through defenders.' },
  { code: 'ELU', label: 'Elusiveness', category: 'offense', description: 'Making defenders miss.' },
  { code: 'BTK', label: 'Break Tackle', category: 'offense', description: 'Strength and size advantage over tacklers.' },
  { code: 'JKK', label: 'Juke', category: 'offense', description: 'Effectiveness of jukes in open space.' },
  { code: 'SPM', label: 'Spin', category: 'offense', description: 'Effectiveness of spins in open space.' },
  { code: 'SFA', label: 'Stiff Arm', category: 'offense', description: 'Ability to fend off tacklers.' },
  { code: 'TAK', label: 'Tackling', category: 'defense', description: 'Ability to wrap up and bring down ball carriers.' },
  { code: 'POW', label: 'Hit Power', category: 'defense', description: 'Chance to cause fumbles on contact.' },
  { code: 'BSH', label: 'Block Shedding', category: 'defense', description: 'Capability to defeat blockers and get to the ball.' },
  { code: 'PMK', label: 'Power Moves', category: 'defense', description: 'Using strength to overpower blockers.' },
  { code: 'FMK', label: 'Finesse Moves', category: 'defense', description: 'Using speed and technique to beat blockers.' },
  { code: 'PUR', label: 'Pursuit', category: 'defense', description: 'Angle efficiency and speed when tracking ball carriers.' },
  { code: 'PRC', label: 'Play Recognition', category: 'defense', description: 'Identifying runs versus passes early.' },
  { code: 'MCV', label: 'Man Coverage', category: 'defense', description: 'Ability to stick to receivers in man coverage.' },
  { code: 'ZCV', label: 'Zone Coverage', category: 'defense', description: 'Dropping into spots and defending zones.' },
  { code: 'PRS', label: 'Press', category: 'defense', description: 'Effectiveness jamming receivers at the line of scrimmage.' },
  { code: 'KPW', label: 'Kick Power', category: 'specialTeams', description: 'Maximum distance on kicks.' },
  { code: 'KAC', label: 'Kick Accuracy', category: 'specialTeams', description: 'Aiming and timing precision on kicks.' },
];

export const PLAYER_ABILITIES: PlayerAbility[] = [
  {
    id: 'backfield-creator',
    name: 'Backfield Creator',
    type: 'physical',
    category: 'archetype',
    positionGroups: ['QB'],
    description: 'Quarterback archetype from the CFB 26 abilities list.',
  },
  {
    id: 'off-platform',
    name: 'Off Platform',
    type: 'physical',
    category: 'trait',
    positionGroups: ['QB'],
    archetypes: ['Backfield Creator'],
    description: 'Trait tied to Backfield Creator quarterbacks.',
  },
  {
    id: 'on-time',
    name: 'On Time',
    type: 'physical',
    category: 'trait',
    positionGroups: ['QB'],
    archetypes: ['Backfield Creator', 'Pocket Passer'],
    description: 'Trait tied to timing and rhythm passing.',
  },
  {
    id: 'dot',
    name: 'Dot!',
    type: 'physical',
    category: 'trait',
    positionGroups: ['QB', 'WR'],
    description: 'Accuracy or placement boost on eligible passing concepts.',
  },
  {
    id: 'option-king',
    name: 'Option King',
    type: 'physical',
    category: 'trait',
    positionGroups: ['QB'],
    description: 'Boosts option-game execution.',
  },
  {
    id: 'workhorse',
    name: 'Workhorse',
    type: 'physical',
    category: 'trait',
    positionGroups: ['RB', 'WR', 'DL', 'LB', 'S'],
    description: 'Durability and usage-focused ability.',
  },
  {
    id: 'shifty',
    name: 'Shifty',
    type: 'physical',
    category: 'trait',
    positionGroups: ['QB', 'RB', 'WR'],
    description: 'Improves open-field quickness and movement.',
  },
  {
    id: 'sure-hands',
    name: 'Sure Hands',
    type: 'physical',
    category: 'trait',
    positionGroups: ['WR', 'TE'],
    description: 'Improves reliability when catching passes.',
  },
  {
    id: 'strong-grip',
    name: 'Strong Grip',
    type: 'physical',
    category: 'trait',
    positionGroups: ['FB', 'TE', 'OL'],
    description: 'Improves blocking engagement and control.',
  },
  {
    id: 'quick-jump',
    name: 'Quick Jump',
    type: 'physical',
    category: 'trait',
    positionGroups: ['DL', 'CB'],
    description: 'Faster first step for rushers or defenders.',
  },
  {
    id: 'ball-hawk',
    name: 'Ball Hawk',
    type: 'physical',
    category: 'trait',
    positionGroups: ['CB', 'S'],
    description: 'Improves plays on the ball in coverage.',
  },
  { id: 'field-general', name: 'Field General', type: 'mental', category: 'mental', description: 'Mental ability for pre-snap and field awareness.' },
  { id: 'team-player', name: 'Team Player', type: 'mental', category: 'mental', description: 'Mental ability tied to chemistry and role acceptance.' },
  { id: 'winning-time', name: 'Winning Time', type: 'mental', category: 'mental', description: 'Mental ability for high-leverage late-game moments.' },
];
