import type {
  Conference,
  Dynasty,
  Player,
  PlayerProgression,
  Roster,
  Season,
} from './types.js';
import { NCAA_TEAM_CATALOG } from './team-catalog.js';

export const PLACEHOLDER_CONFERENCES: Conference[] = [
  { id: 'sec', name: 'Southeastern Conference', abbreviation: 'SEC' },
  { id: 'big-ten', name: 'Big Ten Conference', abbreviation: 'Big 10' },
  { id: 'big-12', name: 'Big 12 Conference', abbreviation: 'B12' },
  { id: 'acc', name: 'Atlantic Coast Conference', abbreviation: 'ACC' },
  { id: 'aac', name: 'American Athletic Conference', abbreviation: 'AAC' },
  { id: 'c-usa', name: 'Conference USA', abbreviation: 'C-USA' },
  { id: 'mac', name: 'Mid-American Conference', abbreviation: 'MAC' },
  { id: 'mwc', name: 'Mountain West Conference', abbreviation: 'MWC' },
  { id: 'sun-belt', name: 'Sun Belt Conference', abbreviation: 'SBC' },
  { id: 'pac-12', name: 'Pac-12', abbreviation: 'PAC' },
  { id: 'independent', name: 'FBS Independents', abbreviation: 'IND' },
  { id: 'future', name: 'Future/Placeholder Programs', abbreviation: 'FUT' },
];

export const PLACEHOLDER_TEAMS = NCAA_TEAM_CATALOG;

function makePlayer(
  id: string,
  teamId: string,
  first: string,
  last: string,
  position: Player['position'],
  overall: number,
  classYear: Player['classYear'],
  jersey: number
): Player {
  return {
    id,
    teamId,
    firstName: first,
    lastName: last,
    position,
    jerseyNumber: jersey,
    classYear,
    ratings: { overall, speed: overall - 2, awareness: overall - 1 },
    developmentTrait: overall >= 90 ? 'Star' : 'Normal',
  };
}

export const PLACEHOLDER_ROSTERS: Record<string, Roster> = {
  'team-alabama': {
    teamId: 'team-alabama',
    updatedAt: new Date().toISOString(),
    depthChart: [
      { position: 'QB', depth: 1, playerId: 'p-bama-qb1' },
      { position: 'RB', depth: 1, playerId: 'p-bama-rb1' },
      { position: 'WR', depth: 1, playerId: 'p-bama-wr1' },
    ],
    players: [
      {
        ...makePlayer('p-bama-qb1', 'team-alabama', 'Ty', 'Simpson', 'QB', 96, 'SR', 6),
        archetype: 'Backfield Creator',
        abilities: [
          {
            id: 'backfield-creator',
            name: 'Backfield Creator',
            type: 'physical',
            category: 'archetype',
            positionGroups: ['QB'],
          },
          {
            id: 'off-platform',
            name: 'Off Platform',
            type: 'physical',
            category: 'trait',
            level: 'gold',
            positionGroups: ['QB'],
            archetypes: ['Backfield Creator'],
          },
          {
            id: 'on-time',
            name: 'On Time',
            type: 'physical',
            category: 'trait',
            level: 'silver',
            positionGroups: ['QB'],
            archetypes: ['Backfield Creator', 'Pocket Passer'],
          },
        ],
      },
      makePlayer('p-bama-rb1', 'team-alabama', 'Jam', 'Miller', 'RB', 97, 'SR', 26),
      makePlayer('p-bama-wr1', 'team-alabama', 'Isaiah', 'Horton', 'WR', 91, 'SR', 1),
      makePlayer('p-bama-wr2', 'team-alabama', 'Jalen', 'Milroe', 'WR', 84, 'JR', 4),
    ],
  },
  'team-georgia': {
    teamId: 'team-georgia',
    updatedAt: new Date().toISOString(),
    depthChart: [
      { position: 'QB', depth: 1, playerId: 'p-uga-qb1' },
      { position: 'RB', depth: 1, playerId: 'p-uga-rb1' },
    ],
    players: [
      makePlayer('p-uga-qb1', 'team-georgia', 'Carson', 'Beck', 'QB', 91, 'SR', 15),
      makePlayer('p-uga-rb1', 'team-georgia', 'Trevon', 'Etienne', 'RB', 88, 'JR', 23),
      makePlayer('p-uga-wr1', 'team-georgia', 'Dominic', 'Lovett', 'WR', 86, 'SR', 0),
    ],
  },
  'team-ohio-state': {
    teamId: 'team-ohio-state',
    updatedAt: new Date().toISOString(),
    depthChart: [{ position: 'QB', depth: 1, playerId: 'p-osu-qb1' }],
    players: [
      makePlayer('p-osu-qb1', 'team-ohio-state', 'Will', 'Howard', 'QB', 90, 'SR', 18),
      makePlayer('p-osu-rb1', 'team-ohio-state', 'Quinshon', 'Judkins', 'RB', 91, 'JR', 1),
      makePlayer('p-osu-wr1', 'team-ohio-state', 'Emeka', 'Egbuka', 'WR', 92, 'SR', 2),
    ],
  },
};

export const PLACEHOLDER_DYNASTY: Dynasty = {
  id: 'dynasty-demo',
  name: 'Demo Dynasty 2026',
  userTeamId: 'team-alabama',
  currentSeasonYear: 2026,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  recruitingClasses: [
    {
      classYear: 2027,
      recruits: [
        {
          id: 'rec-1',
          dynastyId: 'dynasty-demo',
          classYear: 2027,
          firstName: 'Marcus',
          lastName: 'Johnson',
          position: 'WR',
          stars: 5,
          nationalRank: 12,
          state: 'TX',
          committedTeamId: 'team-alabama',
          ratings: { overall: 94 },
        },
      ],
    },
  ],
  seasons: [
    {
      id: 'season-2026',
      dynastyId: 'dynasty-demo',
      year: 2026,
      label: '2026 Season',
      schedule: [
        {
          id: 'g1',
          seasonId: 'season-2026',
          week: 1,
          homeTeamId: 'team-alabama',
          awayTeamId: 'team-georgia',
          isConferenceGame: true,
          isPlayed: false,
        },
        {
          id: 'g2',
          seasonId: 'season-2026',
          week: 2,
          homeTeamId: 'team-ohio-state',
          awayTeamId: 'team-alabama',
          isPlayed: false,
        },
      ],
      standings: [
        { teamId: 'team-alabama', wins: 0, losses: 0, ranking: 3 },
        { teamId: 'team-georgia', wins: 0, losses: 0, ranking: 1 },
        { teamId: 'team-ohio-state', wins: 0, losses: 0, ranking: 2 },
      ],
    },
  ] as Season[],
};

export const PLACEHOLDER_PROGRESSION: PlayerProgression[] = [
  {
    playerId: 'p-bama-qb1',
    playerName: 'Ty Simpson',
    teamId: 'team-alabama',
    position: 'QB',
    snapshots: [
      {
        id: 'prog-qb-carter-2026-pre',
        playerId: 'p-bama-qb1',
        teamId: 'team-alabama',
        capturedAt: '2026-08-01T00:00:00Z',
        seasonYear: 2026,
        week: 0,
        label: 'FR Preseason',
        ratings: {
          overall: 72,
          speed: 82,
          acceleration: 84,
          awareness: 61,
          throwPower: 86,
          shortAccuracy: 70,
          mediumAccuracy: 67,
          deepAccuracy: 64,
          throwOnRun: 76,
          playAction: 63,
        },
      },
      {
        id: 'prog-qb-carter-2026-end',
        playerId: 'p-bama-qb1',
        teamId: 'team-alabama',
        capturedAt: '2026-12-12T00:00:00Z',
        seasonYear: 2026,
        week: 15,
        label: 'FR Bowl Week',
        ratings: {
          overall: 76,
          speed: 83,
          acceleration: 85,
          awareness: 66,
          throwPower: 87,
          shortAccuracy: 74,
          mediumAccuracy: 71,
          deepAccuracy: 68,
          throwOnRun: 78,
          playAction: 68,
        },
        overallDelta: 4,
      },
      {
        id: 'prog-qb-carter-2027-pre',
        playerId: 'p-bama-qb1',
        teamId: 'team-alabama',
        capturedAt: '2027-08-01T00:00:00Z',
        seasonYear: 2027,
        week: 0,
        label: 'SO Preseason',
        ratings: {
          overall: 81,
          speed: 84,
          acceleration: 86,
          awareness: 73,
          throwPower: 88,
          shortAccuracy: 80,
          mediumAccuracy: 77,
          deepAccuracy: 74,
          throwOnRun: 82,
          playAction: 75,
        },
        overallDelta: 5,
      },
      {
        id: 'prog-qb-carter-2027-end',
        playerId: 'p-bama-qb1',
        teamId: 'team-alabama',
        capturedAt: '2027-12-12T00:00:00Z',
        seasonYear: 2027,
        week: 15,
        label: 'SO Bowl Week',
        ratings: {
          overall: 84,
          speed: 84,
          acceleration: 86,
          awareness: 78,
          throwPower: 89,
          shortAccuracy: 83,
          mediumAccuracy: 80,
          deepAccuracy: 77,
          throwOnRun: 84,
          playAction: 79,
        },
        overallDelta: 3,
      },
      {
        id: 'prog-qb-carter-2028-pre',
        playerId: 'p-bama-qb1',
        teamId: 'team-alabama',
        capturedAt: '2028-08-01T00:00:00Z',
        seasonYear: 2028,
        week: 0,
        label: 'JR Preseason',
        ratings: {
          overall: 88,
          speed: 85,
          acceleration: 87,
          awareness: 84,
          throwPower: 90,
          shortAccuracy: 87,
          mediumAccuracy: 85,
          deepAccuracy: 82,
          throwOnRun: 86,
          playAction: 84,
        },
        overallDelta: 4,
      },
      {
        id: 'prog-qb-carter-2028-end',
        playerId: 'p-bama-qb1',
        teamId: 'team-alabama',
        capturedAt: '2028-12-12T00:00:00Z',
        seasonYear: 2028,
        week: 15,
        label: 'JR Bowl Week',
        ratings: {
          overall: 91,
          speed: 85,
          acceleration: 87,
          awareness: 88,
          throwPower: 91,
          shortAccuracy: 90,
          mediumAccuracy: 88,
          deepAccuracy: 86,
          throwOnRun: 88,
          playAction: 88,
        },
        overallDelta: 3,
      },
      {
        id: 'prog-qb-carter-2029-pre',
        playerId: 'p-bama-qb1',
        teamId: 'team-alabama',
        capturedAt: '2029-08-01T00:00:00Z',
        seasonYear: 2029,
        week: 0,
        label: 'SR Preseason',
        ratings: {
          overall: 94,
          speed: 86,
          acceleration: 88,
          awareness: 92,
          throwPower: 92,
          shortAccuracy: 93,
          mediumAccuracy: 91,
          deepAccuracy: 89,
          throwOnRun: 90,
          playAction: 91,
        },
        overallDelta: 3,
      },
      {
        id: 'prog-qb-carter-2029-end',
        playerId: 'p-bama-qb1',
        teamId: 'team-alabama',
        capturedAt: '2029-12-12T00:00:00Z',
        seasonYear: 2029,
        week: 15,
        label: 'SR Bowl Week',
        ratings: {
          overall: 96,
          speed: 86,
          acceleration: 88,
          awareness: 95,
          throwPower: 93,
          shortAccuracy: 95,
          mediumAccuracy: 94,
          deepAccuracy: 92,
          throwOnRun: 91,
          playAction: 94,
        },
        overallDelta: 2,
      },
    ],
  },
  {
    playerId: 'p-bama-rb1',
    playerName: 'Jam Miller',
    teamId: 'team-alabama',
    position: 'RB',
    snapshots: [
      {
        id: 'prog-rb-brooks-2026-pre',
        playerId: 'p-bama-rb1',
        teamId: 'team-alabama',
        capturedAt: '2026-08-01T00:00:00Z',
        seasonYear: 2026,
        week: 0,
        label: 'FR Preseason',
        ratings: {
          overall: 68,
          speed: 91,
          acceleration: 93,
          agility: 88,
          awareness: 56,
          ballCarrierVision: 65,
          trucking: 61,
          elusiveness: 84,
          breakTackle: 66,
          juke: 82,
          spin: 79,
          carry: 70,
        },
      },
      {
        id: 'prog-rb-brooks-2026-end',
        playerId: 'p-bama-rb1',
        teamId: 'team-alabama',
        capturedAt: '2026-12-12T00:00:00Z',
        seasonYear: 2026,
        week: 15,
        label: 'FR Bowl Week',
        ratings: {
          overall: 73,
          speed: 92,
          acceleration: 94,
          agility: 90,
          awareness: 62,
          ballCarrierVision: 71,
          trucking: 64,
          elusiveness: 87,
          breakTackle: 71,
          juke: 85,
          spin: 82,
          carry: 76,
        },
        overallDelta: 5,
      },
      {
        id: 'prog-rb-brooks-2027-pre',
        playerId: 'p-bama-rb1',
        teamId: 'team-alabama',
        capturedAt: '2027-08-01T00:00:00Z',
        seasonYear: 2027,
        week: 0,
        label: 'SO Preseason',
        ratings: {
          overall: 79,
          speed: 93,
          acceleration: 95,
          agility: 92,
          awareness: 70,
          ballCarrierVision: 78,
          trucking: 69,
          elusiveness: 90,
          breakTackle: 78,
          juke: 89,
          spin: 86,
          carry: 82,
        },
        overallDelta: 6,
      },
      {
        id: 'prog-rb-brooks-2027-end',
        playerId: 'p-bama-rb1',
        teamId: 'team-alabama',
        capturedAt: '2027-12-12T00:00:00Z',
        seasonYear: 2027,
        week: 15,
        label: 'SO Bowl Week',
        ratings: {
          overall: 84,
          speed: 94,
          acceleration: 95,
          agility: 93,
          awareness: 76,
          ballCarrierVision: 84,
          trucking: 73,
          elusiveness: 92,
          breakTackle: 83,
          juke: 92,
          spin: 89,
          carry: 86,
        },
        overallDelta: 5,
      },
      {
        id: 'prog-rb-brooks-2028-pre',
        playerId: 'p-bama-rb1',
        teamId: 'team-alabama',
        capturedAt: '2028-08-01T00:00:00Z',
        seasonYear: 2028,
        week: 0,
        label: 'JR Preseason',
        ratings: {
          overall: 89,
          speed: 95,
          acceleration: 96,
          agility: 94,
          awareness: 82,
          ballCarrierVision: 89,
          trucking: 77,
          elusiveness: 94,
          breakTackle: 88,
          juke: 94,
          spin: 91,
          carry: 90,
        },
        overallDelta: 5,
      },
      {
        id: 'prog-rb-brooks-2028-end',
        playerId: 'p-bama-rb1',
        teamId: 'team-alabama',
        capturedAt: '2028-12-12T00:00:00Z',
        seasonYear: 2028,
        week: 15,
        label: 'JR Bowl Week',
        ratings: {
          overall: 93,
          speed: 96,
          acceleration: 97,
          agility: 95,
          awareness: 87,
          ballCarrierVision: 93,
          trucking: 81,
          elusiveness: 96,
          breakTackle: 92,
          juke: 96,
          spin: 94,
          carry: 93,
        },
        overallDelta: 4,
      },
      {
        id: 'prog-rb-brooks-2029-pre',
        playerId: 'p-bama-rb1',
        teamId: 'team-alabama',
        capturedAt: '2029-08-01T00:00:00Z',
        seasonYear: 2029,
        week: 0,
        label: 'SR Preseason',
        ratings: {
          overall: 95,
          speed: 96,
          acceleration: 97,
          agility: 96,
          awareness: 91,
          ballCarrierVision: 95,
          trucking: 84,
          elusiveness: 97,
          breakTackle: 94,
          juke: 97,
          spin: 95,
          carry: 95,
        },
        overallDelta: 2,
      },
      {
        id: 'prog-rb-brooks-2029-end',
        playerId: 'p-bama-rb1',
        teamId: 'team-alabama',
        capturedAt: '2029-12-12T00:00:00Z',
        seasonYear: 2029,
        week: 15,
        label: 'SR Bowl Week',
        ratings: {
          overall: 97,
          speed: 97,
          acceleration: 98,
          agility: 97,
          awareness: 94,
          ballCarrierVision: 97,
          trucking: 87,
          elusiveness: 98,
          breakTackle: 96,
          juke: 98,
          spin: 96,
          carry: 97,
        },
        overallDelta: 2,
      },
    ],
  },
  {
    playerId: 'p-bama-wr1',
    playerName: 'Isaiah Horton',
    teamId: 'team-alabama',
    position: 'WR',
    snapshots: [
      {
        id: 'prog-wr-horton-2026-pre',
        playerId: 'p-bama-wr1',
        teamId: 'team-alabama',
        capturedAt: '2026-08-01T00:00:00Z',
        seasonYear: 2026,
        week: 0,
        label: 'FR Preseason',
        ratings: {
          overall: 74,
          speed: 88,
          acceleration: 90,
          awareness: 58,
          catching: 76,
          spectacularCatch: 73,
          catchInTraffic: 70,
          routeRunning: 72,
          release: 69,
        },
      },
      {
        id: 'prog-wr-horton-2026-end',
        playerId: 'p-bama-wr1',
        teamId: 'team-alabama',
        capturedAt: '2026-12-12T00:00:00Z',
        seasonYear: 2026,
        week: 15,
        label: 'FR Bowl Week',
        ratings: {
          overall: 78,
          speed: 89,
          acceleration: 91,
          awareness: 64,
          catching: 80,
          spectacularCatch: 77,
          catchInTraffic: 74,
          routeRunning: 77,
          release: 73,
        },
        overallDelta: 4,
      },
      {
        id: 'prog-wr-horton-2027-pre',
        playerId: 'p-bama-wr1',
        teamId: 'team-alabama',
        capturedAt: '2027-08-01T00:00:00Z',
        seasonYear: 2027,
        week: 0,
        label: 'SO Preseason',
        ratings: {
          overall: 82,
          speed: 90,
          acceleration: 92,
          awareness: 70,
          catching: 84,
          spectacularCatch: 81,
          catchInTraffic: 79,
          routeRunning: 82,
          release: 78,
        },
        overallDelta: 4,
      },
      {
        id: 'prog-wr-horton-2027-end',
        playerId: 'p-bama-wr1',
        teamId: 'team-alabama',
        capturedAt: '2027-12-12T00:00:00Z',
        seasonYear: 2027,
        week: 15,
        label: 'SO Bowl Week',
        ratings: {
          overall: 85,
          speed: 91,
          acceleration: 93,
          awareness: 75,
          catching: 87,
          spectacularCatch: 84,
          catchInTraffic: 82,
          routeRunning: 86,
          release: 82,
        },
        overallDelta: 3,
      },
      {
        id: 'prog-wr-horton-2028-pre',
        playerId: 'p-bama-wr1',
        teamId: 'team-alabama',
        capturedAt: '2028-08-01T00:00:00Z',
        seasonYear: 2028,
        week: 0,
        label: 'JR Preseason',
        ratings: {
          overall: 88,
          speed: 92,
          acceleration: 94,
          awareness: 81,
          catching: 90,
          spectacularCatch: 87,
          catchInTraffic: 85,
          routeRunning: 89,
          release: 86,
        },
        overallDelta: 3,
      },
      {
        id: 'prog-wr-horton-2028-end',
        playerId: 'p-bama-wr1',
        teamId: 'team-alabama',
        capturedAt: '2028-12-12T00:00:00Z',
        seasonYear: 2028,
        week: 15,
        label: 'JR Bowl Week',
        ratings: {
          overall: 90,
          speed: 92,
          acceleration: 94,
          awareness: 85,
          catching: 92,
          spectacularCatch: 89,
          catchInTraffic: 88,
          routeRunning: 91,
          release: 89,
        },
        overallDelta: 2,
      },
      {
        id: 'prog-wr-horton-2029-pre',
        playerId: 'p-bama-wr1',
        teamId: 'team-alabama',
        capturedAt: '2029-08-01T00:00:00Z',
        seasonYear: 2029,
        week: 0,
        label: 'SR Preseason',
        ratings: {
          overall: 91,
          speed: 93,
          acceleration: 95,
          awareness: 88,
          catching: 93,
          spectacularCatch: 91,
          catchInTraffic: 90,
          routeRunning: 93,
          release: 91,
        },
        overallDelta: 1,
      },
    ],
  },
  {
    playerId: 'prog-cb-reed',
    playerName: 'Darius Reed',
    teamId: 'team-georgia',
    position: 'CB',
    snapshots: [
      {
        id: 'prog-cb-reed-2026-pre',
        playerId: 'prog-cb-reed',
        teamId: 'team-georgia',
        capturedAt: '2026-08-01T00:00:00Z',
        seasonYear: 2026,
        week: 0,
        label: 'FR Preseason',
        ratings: {
          overall: 74,
          speed: 92,
          acceleration: 91,
          agility: 88,
          awareness: 59,
          manCoverage: 72,
          zoneCoverage: 68,
          press: 70,
          playRecognition: 60,
          tackle: 61,
        },
      },
      {
        id: 'prog-cb-reed-2026-end',
        playerId: 'prog-cb-reed',
        teamId: 'team-georgia',
        capturedAt: '2026-12-12T00:00:00Z',
        seasonYear: 2026,
        week: 15,
        label: 'FR Bowl Week',
        ratings: {
          overall: 78,
          speed: 93,
          acceleration: 92,
          agility: 90,
          awareness: 65,
          manCoverage: 77,
          zoneCoverage: 73,
          press: 75,
          playRecognition: 67,
          tackle: 64,
        },
        overallDelta: 4,
      },
      {
        id: 'prog-cb-reed-2027-pre',
        playerId: 'prog-cb-reed',
        teamId: 'team-georgia',
        capturedAt: '2027-08-01T00:00:00Z',
        seasonYear: 2027,
        week: 0,
        label: 'SO Preseason',
        ratings: {
          overall: 83,
          speed: 94,
          acceleration: 93,
          agility: 92,
          awareness: 73,
          manCoverage: 84,
          zoneCoverage: 80,
          press: 81,
          playRecognition: 75,
          tackle: 68,
        },
        overallDelta: 5,
      },
      {
        id: 'prog-cb-reed-2027-end',
        playerId: 'prog-cb-reed',
        teamId: 'team-georgia',
        capturedAt: '2027-12-12T00:00:00Z',
        seasonYear: 2027,
        week: 15,
        label: 'SO Bowl Week',
        ratings: {
          overall: 87,
          speed: 95,
          acceleration: 94,
          agility: 93,
          awareness: 80,
          manCoverage: 88,
          zoneCoverage: 85,
          press: 86,
          playRecognition: 82,
          tackle: 71,
        },
        overallDelta: 4,
      },
      {
        id: 'prog-cb-reed-2028-pre',
        playerId: 'prog-cb-reed',
        teamId: 'team-georgia',
        capturedAt: '2028-08-01T00:00:00Z',
        seasonYear: 2028,
        week: 0,
        label: 'JR Preseason',
        ratings: {
          overall: 91,
          speed: 96,
          acceleration: 95,
          agility: 94,
          awareness: 86,
          manCoverage: 93,
          zoneCoverage: 90,
          press: 90,
          playRecognition: 88,
          tackle: 75,
        },
        overallDelta: 4,
      },
      {
        id: 'prog-cb-reed-2028-end',
        playerId: 'prog-cb-reed',
        teamId: 'team-georgia',
        capturedAt: '2028-12-12T00:00:00Z',
        seasonYear: 2028,
        week: 15,
        label: 'JR Bowl Week',
        ratings: {
          overall: 94,
          speed: 97,
          acceleration: 96,
          agility: 95,
          awareness: 91,
          manCoverage: 96,
          zoneCoverage: 94,
          press: 93,
          playRecognition: 92,
          tackle: 78,
        },
        overallDelta: 3,
      },
      {
        id: 'prog-cb-reed-2029-pre',
        playerId: 'prog-cb-reed',
        teamId: 'team-georgia',
        capturedAt: '2029-08-01T00:00:00Z',
        seasonYear: 2029,
        week: 0,
        label: 'SR Preseason',
        ratings: {
          overall: 96,
          speed: 97,
          acceleration: 96,
          agility: 96,
          awareness: 94,
          manCoverage: 98,
          zoneCoverage: 96,
          press: 95,
          playRecognition: 95,
          tackle: 80,
        },
        overallDelta: 2,
      },
      {
        id: 'prog-cb-reed-2029-end',
        playerId: 'prog-cb-reed',
        teamId: 'team-georgia',
        capturedAt: '2029-12-12T00:00:00Z',
        seasonYear: 2029,
        week: 15,
        label: 'SR Bowl Week',
        ratings: {
          overall: 98,
          speed: 98,
          acceleration: 97,
          agility: 97,
          awareness: 97,
          manCoverage: 99,
          zoneCoverage: 98,
          press: 97,
          playRecognition: 98,
          tackle: 83,
        },
        overallDelta: 2,
      },
    ],
  },
];
